In [2]:
#imprting libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data_yelp=pd.read_csv('yelp_labelled.txt',sep='\t',header=None)

In [4]:
data_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [5]:
data_yelp.tail()

0  1
995  I think food should have flavor and texture an...  0
996                           Appetite instantly gone.  0
997  Overall I was not impressed and would not go b...  0
998  The whole experience was underwhelming, and I ...  0
999  Then, as if I hadn't wasted enough of my life ...  0

In [6]:
# review and sentiment
# 0-Negative, 1-Positive

In [7]:
#Assign Column namees
column_name=['Review','Sentiment']
data_yelp.columns=column_name

In [8]:
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [9]:
data_yelp.shape

(1000, 2)

In [14]:
data_amazon=pd.read_csv('amazon_cells_labelled.txt',sep='\t',header=None)
data_amazon.head()

0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [16]:
#Assign Column namees
column_name=['Review','Sentiment']
data_amazon.columns=column_name

In [17]:
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [13]:
data_amazon.shape

(1000, 2)

In [18]:
data_imdb=pd.read_csv('imdb_labelled.txt',sep='\t',header=None)
data_imdb.head()

0  1
0  A very, very, very slow-moving, aimless movie ...  0
1  Not sure who was more lost - the flat characte...  0
2  Attempting artiness with black & white and cle...  0
3       Very little music or anything to speak of.    0
4  The best scene in the movie was when Gerardo i...  1

In [19]:
#Assign Column namees
column_name=['Review','Sentiment']
data_imdb.columns=column_name

In [20]:
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [21]:
data_imdb.shape

(748, 2)

In [22]:
#Append all the data in a single dataframe

In [23]:
data=data_yelp.append([data_amazon,data_imdb],ignore_index=True)

In [24]:
data.shape

(2748, 2)

In [25]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [26]:
#check distribution of sentiments

In [27]:
data['Sentiment'].value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [28]:
#check for null values
data.isnull().sum()

Review       0
Sentiment    0
dtype: int64

In [30]:
x=data['Review']
y=data['Sentiment']

## 2. Data Cleaning

In [43]:
import string
import spacy
nlp=spacy.load('en_core_web_sm')

In [44]:
punct=string.punctuation

In [45]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [46]:
from spacy.lang.en.stop_words import STOP_WORDS

In [47]:
stopwords=list(STOP_WORDS)

In [48]:
stopwords

['yours',
 'whether',
 'say',
 'over',
 'someone',
 'i',
 'amount',
 'toward',
 'and',
 'ever',
 'hence',
 'whenever',
 'get',
 'than',
 'for',
 'first',
 'go',
 'hundred',
 'enough',
 'what',
 'whereby',
 'along',
 'so',
 'seemed',
 'is',
 'around',
 'such',
 'between',
 '‘ll',
 'per',
 'those',
 'perhaps',
 'both',
 'onto',
 'thus',
 'if',
 'yourselves',
 'quite',
 'any',
 'through',
 'behind',
 'on',
 'used',
 'became',
 'twelve',
 'except',
 'anyhow',
 'well',
 'your',
 'could',
 'name',
 '’ll',
 'five',
 'upon',
 'top',
 'about',
 'should',
 'into',
 'latterly',
 'something',
 'already',
 'this',
 'had',
 "n't",
 'under',
 'no',
 '‘ve',
 'at',
 'among',
 'every',
 'very',
 'be',
 'does',
 'ca',
 'whither',
 'somehow',
 'nor',
 'sixty',
 'of',
 'we',
 'twenty',
 'since',
 'rather',
 'made',
 'anyone',
 'was',
 'one',
 'much',
 'which',
 'becoming',
 'via',
 'see',
 'me',
 'back',
 'us',
 'how',
 'her',
 'side',
 'always',
 'been',
 'neither',
 'he',
 'as',
 'otherwise',
 'though',


In [49]:
def text_data_cleaning(sentence):
    doc=nlp(sentence)
    
    tokens=[]
    for token in doc:
        if token.lemma_!="-PRON-":
            temp=token.lemma_.lower().strip()
        else:
            temp=token.lower_
        tokens.append(temp)
        
    cleaned_tokens=[]
    for token in tokens:
        if token not in stopwords and token not in punct:
            cleaned_tokens.append(token)
    return cleaned_tokens

In [51]:
text_data_cleaning("Hello all, It's a beautiful day outside there!")
#stopwords and punctuations removed

['hello', 'beautiful', 'day', 'outside']

### Vectorization Feature Engineering (TF-IDF)

In [55]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [56]:
tfidf=TfidfVectorizer(tokenizer=text_data_cleaning)

In [57]:
classifier=LinearSVC()

### Train the model

In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [59]:
x_train.shape,x_test.shape

((2198,), (550,))

In [60]:
x_train.head()

2572    An Italian reviewer called this "a small, grea...
526                          And it was way to expensive.
1509    As an earlier review noted, plug in this charg...
144     Nice blanket of moz over top but i feel like t...
2483    The film gives meaning to the phrase, "Never i...
Name: Review, dtype: object

### Fit the x_train and y_train

In [62]:
clf=Pipeline([('tfidf',tfidf), ('clf',classifier)])

In [64]:
clf.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=<function text_data_cleaning at 0x0000020711F24F70>,
                                 use_idf=True, vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_inter

### Predict the Test set results

In [72]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [73]:
y_pred=clf.predict(x_test)

In [74]:
#confusion_matrix
confusion_matrix(y_test,y_pred)

array([[202,  77],
       [ 47, 224]], dtype=int64)

In [75]:
#classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.72      0.77       279
           1       0.74      0.83      0.78       271

    accuracy                           0.77       550
   macro avg       0.78      0.78      0.77       550
weighted avg       0.78      0.77      0.77       550



In [76]:
accuracy_score(y_test,y_pred)

0.7745454545454545

In [77]:
clf.predict(["Wow, Iam learning NLP. It is fun"])

array([1], dtype=int64)

In [79]:
#output 1 , that means negative

In [78]:
clf.predict(["It's hard to learn new things!"])

array([0], dtype=int64)

In [ ]:
#output 0 , that means negative